# Generated by Django 5.2.12 on 2026-03-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('PLN', 'Polish Zloty')], default='EUR', max_length=3),
        ),
    ]
