# Generated by Django 5.2.12 on 2026-03-28 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bankaccount_reserved_balance'),
        ('transactions', '0003_alter_transaction_processed_at_alter_transfer_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.UniqueConstraint(fields=('initiated_by', 'idempotency_key'), name='unique_transfer_idempotency_key_per_user'),
        ),
    ]
